version: "3.9"

services:
  web:
    build: .
    image: reporter:latest
    ports:
      - "8093:8093"
    env_file:
      - .env
    restart: always
    depends_on:
      - sql

  sql:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - reporter-data:/var/lib/postgresql/data

volumes:
  reporter-data: